# Generated by Django 3.2.1 on 2021-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
