# Generated by Django 3.2.1 on 2021-05-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20210508_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='p_password1',
            new_name='p_pass1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_password2',
            new_name='p_pass2',
        ),
    ]
