# Generated by Django 3.2.1 on 2021-05-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20210508_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_pass1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_pass2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
