# Generated by Django 3.2.1 on 2021-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20210509_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_emailid',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='s_emailid',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
