# Generated by Django 3.2.1 on 2021-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20210509_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='s_govcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
