# Generated by Django 3.2.1 on 2021-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_supplier_s_govcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('bed', models.CharField(choices=[('ICU', 'ICU beds'), ('Ventilator', 'Ventilator beds'), ('ICU+Ventilator', 'ICU+Ventilator beds')], max_length=40)),
            ],
        ),
    ]
