# Generated by Django 3.2.1 on 2021-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_auto_20210521_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='oxygen',
            field=models.CharField(choices=[('cylinder', 'Oxygen Cylinder'), ('refill', 'Oxygen Cylinder Refill')], max_length=40, null=True),
        ),
    ]
