# Generated by Django 3.2.1 on 2021-06-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_auto_20210602_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oxygen',
            old_name='iv_district',
            new_name='o_district',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='iv_state',
            new_name='o_state',
        ),
    ]
