# Generated by Django 3.2.1 on 2021-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0013_auto_20210602_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='s_password',
            new_name='s_pass1',
        ),
        migrations.AddField(
            model_name='supplier',
            name='s_pass2',
            field=models.CharField(blank=True, default='name4587', max_length=40, null=True),
        ),
    ]
