# Generated by Django 3.2.1 on 2021-06-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0014_auto_20210607_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='s_pass1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='s_pass2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
