# Generated by Django 3.2.1 on 2021-06-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0015_auto_20210607_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icuventilator',
            old_name='s_icu_ventilator',
            new_name='s_icu_ventilator_id',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='s_oxygenr',
            new_name='s_oxygen_id',
        ),
        migrations.RenameField(
            model_name='ventilator',
            old_name='s_ventilator',
            new_name='s_ventilator_id',
        ),
    ]
